name: Update fire and flood maps
on:
  schedule:
    - cron: 0 0/4 * * *

jobs:
  update_charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # - name: Update BC flood warning chart
      #   env: 
      #       DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
      #   run: |
      #     python3 script-bcfloodmap.py

      - name: Update BC fire map
        env: 
            DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: |
          python3 script-bcfiremap.py

      - name: Update Alta. fire map
        env: 
            DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: |
          python3 script-abfiremap.py

      
